### ISSUE TITLE
Differences with Validation Examples

### ISSUE THREAD

**Issue by seechuan** [eeveetza/javaP2001#2]
Was verifying the individual loss values in Validation_examples_ITU-R_P_2001_prof4_results.csv from the ITU website. Found that there are differences in the overall Lb and Lbm3, Lbs values caused by different implementation in tl_troposcatter() method as compared to that in the ITU-R P2001-4 equations. Is this Java implementation for the upcoming 2001-5 spec in study group 3 or the implementation is not correct when compared with 2001-4?

**Comment by eeveetza** [comment]
You are correct, the development branch dev-5 that corresponds to the upcoming Rec. ITU-R P.2001-5 was merged by mistake to the main. The main branch is now reverted to correspond to the reference software implementation from ITU-R SG3 web page, including the validation examples. This above commit ([Correcting Issue](https://github.com/eeveetza/javaP2001/commit/4c41255f3eb3d106717e088564a88b059f6909b8) https://github.com/eeveetza/javaP2001/issues/2) should be resolving the issue, that could be closed. Please let me know if this is the case or if the issue persists.

**Comment by seechuan** [comment]
The validation examples now matches the output exactly. Thanks.
